title:            learning to code from scratch(ish)
description:      A blog about learning to code on FreeCodeCamp as someone from a humanities and social science background.
url:              #http://emilyeye.github.io/
signoff:          emily
disqus_shortname: eyecode
facebook_appid:   821309421312495 # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-72213722-1 # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://emilyeye.github.io
    external:     false
  - name:         GitHub
    url:          http://github.com/emilyeye
    external:     true
  - name:         XML Feed
    url:          /feed.xml
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
